### PR TITLE
Files tab altendky requirements fixup

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by bsberry** [comment]
@altendky Is this PR still needed? I've lost track of the current state of the requirements files.

**Comment by altendky** [comment]
@bsberry, it looks like it's still relevant, yes.  I do have a 'working' setup for locking against Linux/macOS/Windows all with one command from one system (offloads it to an Azure Pipelines build and collects the results) but I want to clean it up a bit before 'rolling it out'.

**Comment by altendky** [comment]
Well, still relevant as long as the `base.in` changes look sensible to you.  Did you somewhere point out also needing `certitude` on Windows or somesuch?

**Comment by bsberry** [comment]
Actually I ended up removing `certitude` since it didn't work on Windows and using `certifi` instead which seems to work. ( https://github.com/bsberry/st/commit/7ba7c1935691d04c4344cb071b561bc659dec305 )

**Pull request closed without merging**
